### ISSUE TITLE
ping pong example improvement

### ISSUE THREAD

**Issue by micuat** [SableRaf/Processing-Experiments#3]
Hi, I know this is an old repo but I noticed
https://github.com/SableRaf/Processing-Experiments/blob/master/2013/Shaders/PingPongFBO/PingPongFBO.pde#L118-L121
can be replaced simply by
```
image(img, 0, 0, width, height);
```
for a huge performance improvement.

**Comment by SableRaf** [comment]
Hi micuat, 

It's now fixed in the following commit: 

https://github.com/SableRaf/Processing-Experiments/commit/f6fdd4e9ecd63d519b1616f777a0f453759421ac

Thanks for your comment :)

Raphaël

**Comment by micuat** [comment]
Wow. Hey Raph, I happened to find this issue. take care and see you soon :)
